name: JP Windows Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  jp-windows:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure SSH Access
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Prepare Tool Environment
        run: |
          git clone --depth 1 git@github.com:beichen23333/BlueArchive-Translation.git tool
          git clone --depth 1 git@github.com:bluearchive-cafe/bluearchive-cafe-api-launcher-jp.git bluearchive-cafe-api-launcher-jp
          git clone --depth 1 git@github.com:bluearchive-cafe/bluearchive-cafe-launcher-pkg-ba-jp.git bluearchive-cafe-launcher-pkg-ba-jp
          git clone --depth 1 git@github.com:bluearchive-cafe/PC-app.git PC-app
          cp -r tool/* . && rm -rf tool

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run JP Windows URL update until commit success
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          python update_windows_url.py

      - name: Decide whether to update addressable
        run: |
          echo "NEED_UPDATE=true" >> $GITHUB_ENV

      - name: Run JP Windows addressable update
        if: env.NEED_UPDATE == 'true'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
        run: python update_windows.py

      - name: Run JP update
        run: |
          cd bluearchive-cafe-launcher-pkg-ba-jp
          git add .
          git commit -m "update" || exit 0
          git push

          cd bluearchive-cafe-api-launcher-jp
          git add .
          git commit -m "update" || exit 0
          git push
